version: '3.8'

services:
  qr_code_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - QR_CODE_DIR=/app/qr_codes
      - FILL_COLOR=red
      - BACK_COLOR=white
    volumes:
      - ./qr_codes:/app/qr_codes  # Maps local qr_codes to container
    command: --url http://www.njit.edu
